# Generated by Django 3.0.5 on 2021-04-06 19:45

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=300, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=300, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='eventinvitee',
            name='event_id',
            field=models.IntegerField(validators=[core.models.ValidateInteger]),
        ),
        migrations.AlterField(
            model_name='eventinvitee',
            name='user_id',
            field=models.IntegerField(validators=[core.models.ValidateInteger]),
        ),
        migrations.AlterField(
            model_name='item',
            name='detail',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='lists',
            name='description',
            field=models.CharField(max_length=300, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='lists',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='list_id',
            field=models.IntegerField(validators=[core.models.ValidateInteger]),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.IntegerField(validators=[core.models.ValidateInteger]),
        ),
    ]
